/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;
/**
 *
 * @author dennis adzua firdaus
 */
public class DataPasien extends javax.swing.JFrame {
private  Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form DataPasien
     */
    public DataPasien() {
        initComponents();
        kosong();
        aktif();
        datatable();
        setLocationRelativeTo(null);
    }
    protected void datatable() {
     Object[] baris ={"Id Pasien","Nama Pasien","Nama Suami","Tanggal Lahir","NIk","No.Tlp","Alamat"};
    tabmode = new DefaultTableModel(null, baris);
     String cari=txtCari1.getText();
     
     
     try{
         String sql = "SELECT * FROM data_pasien where IdPasien like '%"+cari+"%' or NamaPasien like'%"+cari+"%' or NamaSuami like'%"+cari+"%' order by IdPasien asc";
         Statement stat = conn.createStatement();
         ResultSet hasil = stat.executeQuery(sql);
         while (hasil.next()){
             tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7)
            });
         } 
         jtPasien1.setModel(tabmode);
     } catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
     }
    }

    protected void aktif() {
        txtIdPasien.requestFocus();
    }

    protected void kosong() {
        txtIdPasien.setText("");
        txtNamaPasien.setText("");
        txtNamaSuami.setText("");
        txtdate.setText("");
        txtNIK.setText("");
        txtNoTlp.setText("");
        txtAlamat.setText("");
        txtCari1.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNamaPasien = new javax.swing.JLabel();
        jlNamaSuami = new javax.swing.JLabel();
        jlNIK = new javax.swing.JLabel();
        jlAlamat = new javax.swing.JLabel();
        txtIdPasien = new javax.swing.JTextField();
        txtNamaSuami = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        jlNoTlp = new javax.swing.JLabel();
        txtNoTlp = new javax.swing.JTextField();
        jbSimpan = new javax.swing.JButton();
        jbUbah = new javax.swing.JButton();
        jbHapus = new javax.swing.JButton();
        jbSelesai = new javax.swing.JButton();
        jlIdPasien = new javax.swing.JLabel();
        txtNamaPasien = new javax.swing.JTextField();
        jlJenisKelamin = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbCari1 = new javax.swing.JButton();
        txtCari1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtPasien1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Pasien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(420, 420, 420))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jlNamaPasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNamaPasien.setForeground(new java.awt.Color(255, 255, 255));
        jlNamaPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee.png"))); // NOI18N
        jlNamaPasien.setText("Nama Pasien");

        jlNamaSuami.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNamaSuami.setForeground(new java.awt.Color(255, 255, 255));
        jlNamaSuami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man.png"))); // NOI18N
        jlNamaSuami.setText("Nama Suami");

        jlNIK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNIK.setForeground(new java.awt.Color(255, 255, 255));
        jlNIK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/id-card.png"))); // NOI18N
        jlNIK.setText("NIK");

        jlAlamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlAlamat.setForeground(new java.awt.Color(255, 255, 255));
        jlAlamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location.png"))); // NOI18N
        jlAlamat.setText("Alamat");

        txtIdPasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNamaSuami.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNamaSuami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSuamiActionPerformed(evt);
            }
        });

        txtNIK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });

        jlNoTlp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNoTlp.setForeground(new java.awt.Color(255, 255, 255));
        jlNoTlp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone-call.png"))); // NOI18N
        jlNoTlp.setText("No.Tlp");

        txtNoTlp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNoTlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTlpActionPerformed(evt);
            }
        });

        jbSimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jbSimpan.setText("Simpan");
        jbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanActionPerformed(evt);
            }
        });

        jbUbah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbUbah.setText("Ubah");
        jbUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbahActionPerformed(evt);
            }
        });

        jbHapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbHapus.setText("Hapus");
        jbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHapusActionPerformed(evt);
            }
        });

        jbSelesai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbSelesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-door.png"))); // NOI18N
        jbSelesai.setText("Kembali");
        jbSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelesaiActionPerformed(evt);
            }
        });

        jlIdPasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlIdPasien.setForeground(new java.awt.Color(255, 255, 255));
        jlIdPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee.png"))); // NOI18N
        jlIdPasien.setText("Id Pasien");

        txtNamaPasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlJenisKelamin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlJenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        jlJenisKelamin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equality.png"))); // NOI18N
        jlJenisKelamin.setText("Tanggal Lahir");

        txtdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jbSimpan)
                .addGap(18, 18, 18)
                .addComponent(jbUbah)
                .addGap(18, 18, 18)
                .addComponent(jbHapus)
                .addGap(18, 18, 18)
                .addComponent(jbSelesai)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaSuami, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlIdPasien)
                                .addComponent(jlNoTlp)
                                .addComponent(jlJenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlNIK))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlNamaPasien)
                                .addComponent(jlNamaSuami, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtNIK)
                            .addComponent(txtNoTlp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdPasien)
                    .addComponent(txtIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNamaPasien)
                    .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaSuami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNamaSuami))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlJenisKelamin)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNIK))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNoTlp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSimpan)
                    .addComponent(jbUbah)
                    .addComponent(jbHapus)
                    .addComponent(jbSelesai))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        jbCari1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbCari1.setText("Cari");
        jbCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCari1ActionPerformed(evt);
            }
        });
        jbCari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCari1KeyPressed(evt);
            }
        });

        txtCari1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCari1ActionPerformed(evt);
            }
        });

        jtPasien1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtPasien1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pasien", "Nama pasien", "Nama Suami", "Tanggal Lahir", "NIK", "No.Tlp", "Alamat"
            }
        ));
        jtPasien1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtPasien1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jtPasien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPasien1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtPasien1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbCari1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCari1)
                    .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaSuamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSuamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSuamiActionPerformed

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void txtNoTlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTlpActionPerformed

    private void jbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanActionPerformed

        String sql = "insert into data_pasien Values (?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtIdPasien.getText());
            stat.setString(2, txtNamaPasien.getText());
            stat.setString(3, txtNamaSuami.getText());
            stat.setString(4, txtdate.getText());
            stat.setString(5, txtNIK.getText());
            stat.setString(6, txtNoTlp.getText());
            stat.setString(7, txtAlamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            kosong();
            txtIdPasien.requestFocus();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e);
        }
        datatable();
    }//GEN-LAST:event_jbSimpanActionPerformed

    private void jbUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbahActionPerformed
        String sql = "UPDATE data_pasien SET  NamaPasien=?, NamaSuami=?, TanggalLahir=?, NIK=?, NoTlp=?, Alamat=? WHERE IdPasien=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtNamaPasien.getText());
            stat.setString(2, txtNamaSuami.getText());
            stat.setString(3, txtdate.getText());
            stat.setString(4, txtNIK.getText());
            stat.setString(5, txtNoTlp.getText());
            stat.setString(6, txtAlamat.getText());
            stat.setString(7, txtIdPasien.getText()); // ini untuk WHERE

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            txtIdPasien.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e);
        }
        datatable();
    }//GEN-LAST:event_jbUbahActionPerformed

    private void jbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "DELETE FROM data_pasien WHERE IdPasien = '"+txtIdPasien.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtIdPasien.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_jbHapusActionPerformed

    private void jbSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelesaiActionPerformed
        this.dispose();
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jbSelesaiActionPerformed

    private void jbCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCari1ActionPerformed
        datatable();
    }//GEN-LAST:event_jbCari1ActionPerformed

    private void jbCari1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCari1KeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_jbCari1KeyPressed

    private void txtCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCari1ActionPerformed

    }//GEN-LAST:event_txtCari1ActionPerformed

    private void jtPasien1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtPasien1AncestorAdded

    }//GEN-LAST:event_jtPasien1AncestorAdded

    private void jtPasien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPasien1MouseClicked
        int bar = jtPasien1.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();

        txtIdPasien.setText(a);
        txtNamaPasien.setText(b);
        txtNamaSuami.setText(c);
        txtdate.setText(d);
        txtNIK.setText(e);
        txtNoTlp.setText(f);
        txtAlamat.setText(g);
    }//GEN-LAST:event_jtPasien1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbCari1;
    private javax.swing.JButton jbHapus;
    private javax.swing.JButton jbSelesai;
    private javax.swing.JButton jbSimpan;
    private javax.swing.JButton jbUbah;
    private javax.swing.JLabel jlAlamat;
    private javax.swing.JLabel jlIdPasien;
    private javax.swing.JLabel jlJenisKelamin;
    private javax.swing.JLabel jlNIK;
    private javax.swing.JLabel jlNamaPasien;
    private javax.swing.JLabel jlNamaSuami;
    private javax.swing.JLabel jlNoTlp;
    private javax.swing.JTable jtPasien1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari1;
    private javax.swing.JTextField txtIdPasien;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNamaSuami;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
