/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan; 
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author dennis adzua firdaus
 */
public class Laporan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jblaporandiagnosa = new javax.swing.JButton();
        jblaporangejala = new javax.swing.JButton();
        jblaporanpenyakit = new javax.swing.JButton();
        jblaporanpasien = new javax.swing.JButton();
        jbSelesai1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasil Laporan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));

        jblaporandiagnosa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jblaporandiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jblaporandiagnosa.setText("Laporan Hasil Diagnosa");
        jblaporandiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporandiagnosaActionPerformed(evt);
            }
        });

        jblaporangejala.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jblaporangejala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jblaporangejala.setText("Laporan Data Gejala");
        jblaporangejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporangejalaActionPerformed(evt);
            }
        });

        jblaporanpenyakit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jblaporanpenyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jblaporanpenyakit.setText("Laporan Data Penyakit");
        jblaporanpenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporanpenyakitActionPerformed(evt);
            }
        });

        jblaporanpasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jblaporanpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jblaporanpasien.setText("Laporan Data Pasien");
        jblaporanpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporanpasienActionPerformed(evt);
            }
        });

        jbSelesai1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbSelesai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-door.png"))); // NOI18N
        jbSelesai1.setText("Kembali");
        jbSelesai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelesai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblaporandiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblaporanpenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblaporanpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblaporangejala, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jbSelesai1)
                        .addGap(354, 354, 354))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jblaporanpasien)
                .addGap(18, 18, 18)
                .addComponent(jblaporanpenyakit)
                .addGap(18, 18, 18)
                .addComponent(jblaporangejala)
                .addGap(18, 18, 18)
                .addComponent(jblaporandiagnosa)
                .addGap(52, 52, 52)
                .addComponent(jbSelesai1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblaporanpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporanpasienActionPerformed
      try {
    String reportPath = "src/Laporan/datapasien.jasper";
    JasperPrint jp = JasperFillManager.fillReport(reportPath, null, conn);
    JasperViewer.viewReport(jp, false);
} catch (JRException ex) {
    JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + ex.getMessage());
}

    }//GEN-LAST:event_jblaporanpasienActionPerformed

    private void jblaporanpenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporanpenyakitActionPerformed
         try {
    String reportPath = "src/Laporan/datapenyakit.jasper";
    JasperPrint jp = JasperFillManager.fillReport(reportPath, null, conn);
    JasperViewer.viewReport(jp, false);
} catch (JRException ex) {
    JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + ex.getMessage());
}

    }//GEN-LAST:event_jblaporanpenyakitActionPerformed

    private void jblaporangejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporangejalaActionPerformed
         try {
            String path = "./src/Laporan/datagejala.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada" +ex);
        }
    }//GEN-LAST:event_jblaporangejalaActionPerformed

    private void jbSelesai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelesai1ActionPerformed
        this.dispose();
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jbSelesai1ActionPerformed

    private void jblaporandiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporandiagnosaActionPerformed
        try {
    String reportPath = "src/Laporan/hasildiagnosa.jasper";
    JasperPrint jp = JasperFillManager.fillReport(reportPath, null, conn);
    JasperViewer.viewReport(jp, false);
} catch (JRException ex) {
    JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + ex.getMessage());
}

    }//GEN-LAST:event_jblaporandiagnosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbSelesai1;
    private javax.swing.JButton jblaporandiagnosa;
    private javax.swing.JButton jblaporangejala;
    private javax.swing.JButton jblaporanpasien;
    private javax.swing.JButton jblaporanpenyakit;
    // End of variables declaration//GEN-END:variables
}
