/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;
import java.sql.*;
import koneksi.koneksi;
/**
 *
 * @author dennis adzua firdaus
 */
public class MenuUtama extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBhasildiagnosa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JBdatapasien = new javax.swing.JButton();
        JBdatapenyakit = new javax.swing.JButton();
        JBdatagejala = new javax.swing.JButton();
        JBdiagnosa = new javax.swing.JButton();
        jblaporan = new javax.swing.JButton();
        JBhasildiagnosa1 = new javax.swing.JButton();
        jbadmin = new javax.swing.JButton();
        jbdatarule = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        JBhasildiagnosa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBhasildiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        JBhasildiagnosa.setText("Hasil Diagnosa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aplikasi Sistem Pakar Diagnosis ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penyakit Pada Kandungan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jl. Zambrud Raya, Perum, Taman Griya Asri Blok C7 No. 01, Rt 003 Rw 012, Kel. Cilebut Barat., Kec. Sukaraja, Kab. Bogor, Jawa Barat 16610");

        jbLogOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-door.png"))); // NOI18N
        jbLogOut.setText("Kembali");
        jbLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(290, 290, 290)
                        .addComponent(jbLogOut)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(444, 444, 444))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLogOut)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        JBdatapasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBdatapasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hospitalisation.png"))); // NOI18N
        JBdatapasien.setText("Data Pasien");
        JBdatapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdatapasienActionPerformed(evt);
            }
        });

        JBdatapenyakit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBdatapenyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mask.png"))); // NOI18N
        JBdatapenyakit.setText("Data Penyakit");
        JBdatapenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdatapenyakitActionPerformed(evt);
            }
        });

        JBdatagejala.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBdatagejala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mask.png"))); // NOI18N
        JBdatagejala.setText("Data Gejala");
        JBdatagejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdatagejalaActionPerformed(evt);
            }
        });

        JBdiagnosa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBdiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diagnose.png"))); // NOI18N
        JBdiagnosa.setText("Diagnosa");
        JBdiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdiagnosaActionPerformed(evt);
            }
        });

        jblaporan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jblaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart.png"))); // NOI18N
        jblaporan.setText("Laporan");
        jblaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporanActionPerformed(evt);
            }
        });

        JBhasildiagnosa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JBhasildiagnosa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        JBhasildiagnosa1.setText("Hasil Diagnosa");
        JBhasildiagnosa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBhasildiagnosa1ActionPerformed(evt);
            }
        });

        jbadmin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hacker.png"))); // NOI18N
        jbadmin.setText("Data Admin");
        jbadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbadminActionPerformed(evt);
            }
        });

        jbdatarule.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbdatarule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backup.png"))); // NOI18N
        jbdatarule.setText("Data Rule");
        jbdatarule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdataruleActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nurse.png"))); // NOI18N
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(JBdatapasien)
                .addGap(18, 18, 18)
                .addComponent(JBdatapenyakit)
                .addGap(18, 18, 18)
                .addComponent(JBdatagejala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbdatarule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBdiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBhasildiagnosa1)
                .addGap(18, 18, 18)
                .addComponent(jbadmin)
                .addGap(18, 18, 18)
                .addComponent(jblaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBdiagnosa)
                            .addComponent(jblaporan)
                            .addComponent(JBhasildiagnosa1)
                            .addComponent(jbadmin))
                        .addGap(28, 28, 28))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBdatapasien)
                    .addComponent(JBdatapenyakit)
                    .addComponent(JBdatagejala)
                    .addComponent(jbdatarule))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pregnancy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(537, 537, 537))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBdatapenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdatapenyakitActionPerformed
      DataPenyakit JBdatapenyakit = new DataPenyakit();
       JBdatapenyakit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBdatapenyakitActionPerformed

    private void JBdatagejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdatagejalaActionPerformed
         DataGejala JBdatagejala = new DataGejala();
       JBdatagejala.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBdatagejalaActionPerformed

    private void JBdiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdiagnosaActionPerformed
         Diagnosa JBdiagnosa = new Diagnosa();
       JBdiagnosa.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBdiagnosaActionPerformed

    private void JBdatapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdatapasienActionPerformed
       DataPasien JBdatapasien = new DataPasien();
       JBdatapasien.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBdatapasienActionPerformed

    private void jbLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogOutActionPerformed
        this.dispose();
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jbLogOutActionPerformed

    private void JBhasildiagnosa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBhasildiagnosa1ActionPerformed
        hasildiagnosa JBhasildiagnosa1 = new hasildiagnosa();
       JBhasildiagnosa1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBhasildiagnosa1ActionPerformed

    private void jblaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporanActionPerformed
    Laporan jblaporan = new Laporan();
       jblaporan.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jblaporanActionPerformed

    private void jbadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbadminActionPerformed
    DataAdmin jbadmin = new DataAdmin();
    jbadmin.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbadminActionPerformed

    private void jbdataruleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdataruleActionPerformed
    DataRules jbdatarule = new DataRules();
    jbdatarule.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbdataruleActionPerformed

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBdatagejala;
    private javax.swing.JButton JBdatapasien;
    private javax.swing.JButton JBdatapenyakit;
    private javax.swing.JButton JBdiagnosa;
    private javax.swing.JButton JBhasildiagnosa;
    private javax.swing.JButton JBhasildiagnosa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbLogOut;
    private javax.swing.JButton jbadmin;
    private javax.swing.JButton jbdatarule;
    private javax.swing.JButton jblaporan;
    // End of variables declaration//GEN-END:variables
}
